name: Ruby Gem

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Set up Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - name: npx semantic-release
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        npx semantic-release
      env:
        GH_TOKEN: ${{secrets.GH_TOKEN}}
        GEM_HOST_API_KEY: ${{secrets.GEM_HOST_API_KEY}}
